// <auto-generated />
using System;
using CajaAhorro.Domain.Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CajaAhorro.Domain.Migrations
{
    [DbContext(typeof(AhorroDbContext))]
    [Migration("20260831004536_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("CajaAhorro.Domain.Entidades.Ahorro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaPagoParticipantes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Finalizada")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontoPorNumero")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalNumeros")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ahorros");
                });

            modelBuilder.Entity("CajaAhorro.Domain.Entidades.DetalleAhorro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AhorroId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCobro")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoAEntregar")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroAsignado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SocioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AhorroId");

                    b.HasIndex("SocioId");

                    b.ToTable("DetallesAhorros");
                });

            modelBuilder.Entity("CajaAhorro.Domain.Entidades.Socio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Socios");
                });

            modelBuilder.Entity("CajaAhorro.Domain.Entidades.DetalleAhorro", b =>
                {
                    b.HasOne("CajaAhorro.Domain.Entidades.Ahorro", "PlanAhorro")
                        .WithMany("ListaDetalles")
                        .HasForeignKey("AhorroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CajaAhorro.Domain.Entidades.Socio", "Persona")
                        .WithMany()
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("PlanAhorro");
                });

            modelBuilder.Entity("CajaAhorro.Domain.Entidades.Ahorro", b =>
                {
                    b.Navigation("ListaDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
